name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Node.js
        uses: actions/setup-node@v2
        with:
           node-version: '16'

      - name: npm install
        run: npm install

      - name: Prettier check
        run: npm run check-format

      - name: Jest
        run: npm run test

